name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: build
        run: make CFLAGS='-DENABLE_FEATURE_MAKE_EXTENSIONS=1'

      - name: test
        run: make test
